name: CI
on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Create file
        run: |
          echo "aefasdfasdfasdfasdfasdf" > z-masleeeeeeem.txt
          cat z-masleeeeeeem.txt
      - name: Add
        run: git add test.txt
      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update blocklist files"
        env:
          GIT_USER: GitHub Actions
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
        env:
          GIT_USER: GitHub Actions
