name: CI
on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Create everything list
        run: node scripts/create-everything-list
      - name: Generate AdGuard list
        run: node scripts/generate-adguard.js
      - name: Add files to Git index
        run: git add .
      - name: Commit changes
        run: git commit -m "Update blocklist files by GitHub Actions"
        env:
          GIT_USER: GitHub Actions
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
        env:
          GIT_USER: GitHub Actions
