name: CI
on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Show current directory
        run: |
          pwd
      - run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: node scripts/create-everything-list.js
      - run: node scripts/generate-adguard.js
      - name: Add files to commit
        run: |
          git add .
          git status
      - name: Commit & Push
        uses: actions-x/commit@v6
        with:
          email: contact@sefinek.net
          name: GitHub Actions
          branch: main
